### ISSUE TITLE
Having codeaffine scroll applied to trees/tables can make things slow.

### ISSUE THREAD

**Issue by fabioz** [fappel/xiliary#59] opened 2016-02-18 10:44 UTC
I'm having some issues where Eclipse becomes slow after applying the codeaffine scroll to trees/tables. Firing up visualvm, it seems that the stack below is the place where the code is stuck at (this seems to happen when adding/removing many items from the tree and it can take quite some time before it becomes responsive again -- although it doesn't seem to happen in all machines).

```
"main" #1 prio=6 os_prio=0 tid=0x00000000025da000 nid=0xb64 runnable [0x000000000012d000]
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(OS.java:2443)
	at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1553)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4774)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6024)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
	at org.eclipse.swt.internal.win32.OS.SendMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.SendMessage(OS.java:3402)
	at org.eclipse.swt.widgets.Tree.computeSize(Tree.java:1830)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.ScrollableControl.computeSize(ScrollableControl.java:82)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.ScrollableControl.computePreferredSize(ScrollableControl.java:78)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.SizeComputer.updatePreferredSize(SizeComputer.java:31)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.AdaptionContext.updatePreferredSize(AdaptionContext.java:95)
	at com.codeaffine.eclipse.swt.widget.scrollable.WatchDog.doRun(WatchDog.java:81)
	at com.codeaffine.eclipse.swt.widget.scrollable.WatchDog.lambda$0(WatchDog.java:77)
	at com.codeaffine.eclipse.swt.widget.scrollable.WatchDog$$Lambda$46/1515989129.run(Unknown Source)
	at com.codeaffine.eclipse.swt.widget.scrollable.context.Reconciliation.runWhileSuspended(Reconciliation.java:52)
	at com.codeaffine.eclipse.swt.widget.scrollable.WatchDog.runWithReconciliationSuspended(WatchDog.java:77)
	at com.codeaffine.eclipse.swt.widget.scrollable.WatchDog.run(WatchDog.java:71)
	at org.eclipse.swt.widgets.Display.runTimer(Display.java:4281)
	at org.eclipse.swt.widgets.Display.messageProc(Display.java:3368)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2549)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3767)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
```

**Comment by fappel** [comment] 2016-02-18 11:13
Thank you for providing this performance issue. Commit a4b36f6847183898c5d8d2b8a52bf269148fd275 introduces some performance improvements, including the WatchDog#doRun method listed in the stack trace above. It would be helpful if you could check out the latest version available in the CI repository at http://fappel.github.io/xiliary/development/ to see if this problem still persists. Of course I will check adding/removing a lot of items anyway. But note that the development version hasn't proved production ready yet, so there might be some other surprises in it...

**Comment by fappel** [comment] 2016-02-22 09:33
I did some checks with adding items to an adapted tree using the latest development version. I couldn't measure any significant difference to a non-adapted tree. So, either commit a4b36f6847183898c5d8d2b8a52bf269148fd275 solves the problem, or my setup did not reproduce your usecase. Maybe you could provide some further information what you do to add/remove many items to/from a tree/table.

**Comment by fabioz** [comment] 2016-02-22 13:05
Well, related to the use case, this is when it's applied to the PyDev
Package Explorer, but not all machines experience it, although as a note,
the tree has around 100k items (in deep hierarchies) and this seems to
happen during the tree reconciliation when many things change -- i.e.:
apparently when switching branches in git, which adds/removes many items in
the tree makes such a slowdown appear (and such a slowdown is not observed
when the codeaffinee scroll is not applied to it).

I'll try things with the latest development and will keep you posted.

**Comment by fappel** [comment] 2016-03-21 06:51
Since I couldn't reproduce the problems with the latest version and there hasn't been new information on this topic for a while I close this issue. Feel free to reopen if the problem reappears and/or there are new insights available that can help to reproduce the troublesome behavior.

**Closed by fappel** 2016-03-21 06:51 UTC
Labels: bug
