### ISSUE TITLE
[ScrollableAdapter] SWTException upon Cancel in Preferences in RCP client

### ISSUE THREAD

**Issue by jbuchberger** [fappel/xiliary#55] opened 2015-12-17 11:14 UTC
observed using 0.2.0.20151217-0536 from master repo

org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
	at org.eclipse.swt.widgets.Widget.removeListener(Widget.java:935)
	at org.eclipse.jface.window.ToolTip.deactivate(ToolTip.java:192)
	at org.eclipse.jface.window.ToolTip.toolTipHide(ToolTip.java:448)
	at org.eclipse.jface.window.ToolTip.access$1(ToolTip.java:438)
	at org.eclipse.jface.window.ToolTip$ToolTipOwnerControlListener.handleEvent(ToolTip.java:627)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1137)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1118)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:822)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:460)
(...)
	at org.eclipse.jface.preference.PreferenceNode.disposeResources(PreferenceNode.java:167)
	at org.eclipse.jface.preference.PreferenceDialog$2.run(PreferenceDialog.java:293)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jface.preference.PreferenceDialog.close(PreferenceDialog.java:305)
	at org.eclipse.jface.preference.PreferenceDialog.cancelPressed(PreferenceDialog.java:272)
	at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:237)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	at org.eclipse.jface.window.Window.open(Window.java:803)

**Comment by fappel** [comment] 2015-12-17 13:54
Ouch. I'm not able to reproduce this. Is it possible to provide some additional info on how to trigger the exception?  Obviously, it looks as if it's related to #51, but without being able to reproduce it, it's difficult to develop a solution strategy.

**Comment by jbuchberger** [comment] 2015-12-17 15:02
OK, I'll try to debug to get more details about what's happening.
Hopefully, I get to it before the holidays.

**Comment by fappel** [comment] 2015-12-17 15:15
Meanwhile I've tried it with different workspaces and installations, but no luck in reproducing the problem. Don't push it too hard, since I also can't promise to deliver a fix before the holidays...

**Comment by fappel** [comment] 2016-03-21 06:52
Since I couldn't reproduce the problems with the latest version and there hasn't been new information on this topic for a while I close this issue. Feel free to reopen if the problem reappears and/or there are new insights available that can help to reproduce the troublesome behavior.

**Closed by fappel** 2016-03-21 06:52 UTC
Labels: bug
