### ISSUE TITLE
Some project names and file names listed in Project Explorer in black text - dark theme

### ISSUE THREAD

**Issue by J-KC-Man** [fappel/xiliary#78] opened 2016-10-13 22:52 UTC
Hello, 

Firstly great job on the dark theme, it looks good. Apart from the fact that some project names and file names listed in Project Explorer in black text:

 
![image](https://cloud.githubusercontent.com/assets/9494064/19369869/0bf515f2-91a0-11e6-80d3-eca39d1f6cef.png)

**Comment by fappel** [comment] 2016-10-14 09:30
Thanks for reporting this issue. This looks strange, in particular, as clean sheet should have no influence on the tree item color. So, and I must ask this, the problem does not exist in the dark theme without clean sheet installed? Which Eclipse and OS version are you using? Seems as if the problem is caused by changed git repository content. Hm,...

**Comment by J-KC-Man** [comment] 2016-10-14 12:50
Hi,

Turns out it was an eclipse bug as I uninstalled clean sheet and Eclipse still had the issue. Its actually an Eclipse feature which colours uncommitted changes in black text. To solve this I followed the instructions on comment 28: https://bugs.eclipse.org/bugs/show_bug.cgi?id=430741#c28 

Thanks

**Comment by fappel** [comment] 2016-10-14 13:25
Thanks for the info, I close this issue

**Closed by fappel** 2016-10-14 13:25 UTC
Labels: bug
